org.gradle.jvmargs=-Xmx2500m -XX:MaxMetaspaceSize=768m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=36
buildDir=build
qtGradlePluginType=com.android.application
qtAndroidDir=../.qt-android-runtime/src/android/java
qt5AndroidDir=../.qt-android-runtime/src/android/java
androidPackageName=ing.boykiss.voxora
androidCompileSdkVersion=android-36
androidBuildToolsVersion=36.0.0
androidNdkVersion=27.2.12479018
qtMinSdkVersion=28
qtTargetSdkVersion=36
qtTargetAbiList=arm64-v8a,x86_64
